### ISSUE TITLE
Button doesn't display anything.

### ISSUE THREAD

**Issue by kamodius** [sragia/Exlist#2]
What's the issue?
- Exlist button shows up and is moveable, there are no tooltips/displays anywhere.

What version of Exlist were you using?
- 1.0.6b

Any error logs? Make sure you have errors enabled (`console scriptErrors 1`) or install (recommended) [Bugsack](https://mods.curse.com/addons/wow/BugSack) and [Buggrabber](https://www.curseforge.com/wow/addons/bug-grabber)

- No errors, just doesn't display anything.  I am using TipTac, not sure if they're incompatible.

**Comment by sragia** [comment]
Hi, 
Can't really reproduce this. Seems to work fine with TipTac. Are you sure there's no errors and they are enabled? Maybe tried with other addons disabled?
