### ISSUE TITLE
Conflict with HidingBar: Exlist's tooltip does not hide after mouseout

### ISSUE THREAD

**Issue by class2u** [sragia/Exlist#29]
What's the issue?
Exlist's tooltip does not hide after mouseout.

Steps to reproduce:
1. Install the HidingBar addon.
2. Mouseover Exlist's minimap button.
3. Mouseout the minimap button.

Expected Behaviour:
The Exlist's tooltip hides after mouseout.

Actual Behaviour
The Exlist's tooltip is still there and no way to hide it except /reload.

[I log this issue in HidingBar](https://github.com/sfmict/HidingBar/issues/26) too. The author of HidingBar replies:
I can fix this situation a little, the button must be visible for its script to work. Only the author of the addon will fix this completely.

What version of Exlist were you using?
1.6.11

Did it work before? If so which version?
Did not test.

Tried with other addons disabled?
Yes, enable Exlist and HidingBar only.

Any error logs? Make sure you have errors enabled (`/console scriptErrors 1`) or install (recommended) [Bugsack](https://mods.curse.com/addons/wow/BugSack) and [Buggrabber](https://www.curseforge.com/wow/addons/bug-grabber)

No lua error.

**Comment by sragia** [comment]
Will look into this over weekend

**Comment by sragia** [comment]
Should be fixed with latest release - 1.7.1
