### ISSUE TITLE
The translation of simplified chinese.

### ISSUE THREAD

**Issue by CrisReus** [sragia/Exlist#4]
`if not (GetLocale() == "zhCN") then
  return
end
local L = Exlist.L

L[" Add Item (|cffffffffInput itemID or item name|r)"] = " 新增物品 (|cffffffff输入物品ID 或物品名称|r)"
L[" available!"] = " 可用!"
L[" LFR"] = " 随机"
L["\nCharacter Reputations"] = "\n角色声望"
L["\nWorld Quest rules"] = "\n世界任务规则"
L["Add Faction ID to list"] = "新增势力阵营ID 到清单中"
L["Add Note"] = "新增备注"
L["Add Note to your characters"] = "新增角色备注"
L["Add Quest ID"] = "新增任务ID"
L["Add rules by which addon is going to track world quests. \nFor example, show all world quest that have more than 3 Bloods of Sargeras"] = "新增追踪世界任务规则。\n例如: 显示所有奖励超过 3 个萨格拉斯之血的世界任务"
L["Add World Quest ID"] = "新增世界任务ID"
L["Add World Quests you want to see"] = "新增想要看到的世界任务"
L["Allows user to track different daily or weekly quests"] = "允许追踪不同的日常或周常"
L["Amount"] = "数量"
L["Announce instance reset"] = "通报副本重置"
L["April"] = "四月"
L["Arc"] = "回廊"
L["Archaeology"] = "考古学"
L["Argus Lesser Invasions"] = "阿古斯小入侵"
L["August"] = "八月"
L["Author"] = "作者"
L["avail"] = "可用"
L["available"] = "可用"
L["Available"] = "可用"
L["Available Emissaries"] = "大使"
L["Azerite"] = "艾泽里特"
L["Azerite Power"] = "艾泽里特之力"
L["Back"] = "背部"
L["Background Color"] = "背景颜色"
L["Battle for Azeroth"] = "争霸艾泽拉斯"
L["Best Mythic+"] = "最佳大秘境 "
L["Border Color"] = "边框颜色"
L["BRH"] = "黑鸦"
L["Broken Shore"] = "破碎海岸"
L["Broken Shore Buildings"] = "破碎海岸建筑"
L["Cataclysm"] = "大灾变"
L["Character Title Size"] = "角色标题大小"
L["Characters"] = "角色"
L["Chest"] = "胸部"
L["Chest"] = "胸部"
L["Chest Available"] = "可开宝箱"
L["CoEN"] = "大教堂"
L["Coins"] = "好运符"
L["Collects information about different currencies  and user specified item amounts in inventory"] = "收集各种兑换通货信息，及指定物品在背包中的数量"
L["Completed"] = "已完成"
L["Controls quests that are being tracked by addon\n"] = "控制插件要追踪的任务\n"
L["CoS"] = "群星"
L["Couldn't add item:"] = "无法新增物品:"
L["Curently enabled reputations"] = "目前已启用的声望"
L["Currency"] = "货币"
L["Custom Currency"] = "自定义兑换通货"
L["Custom Reward"] = "自定义奖励"
L["Daily"] = "每日"
L["Daily reset in: "] = "每日重置于: "
L["December"] = "十二月"
L["Defeated"] = "已打过"
L["Delete"] = "删除"
L["Delete"] = "删除"
L["Delete Note?"] = "是否要删除备注?"
L["Delete Note?"] = "是否要删除备注?"
L["Deleting %s-%s failed."] = "删除 %s-%s 失败。"
L["Depleted"] = "已耗尽"
L["Destroyed"] = "已摧毁"
L["DHT"] = "黑心"
L["Do you really want to delete "] = "是否确定要删除 "
L["Do you really want to delete all data for %s-%s?\n\nType \"DELETE\" into the field to confirm."] = "是否要删除 %s-%s 的所有资料? \n\n请在聊天框中输入 \"DELETE\" 确认。"
L["Do you really want to delete this rule?"] = "是否确定删除此规则?"
L["Done"] = "完成"
L["Due to restrictions to API Quest Titles might take couple reloads to appear\n"] = "因API的限制，可能需要重新载入多次后才会显示任务标题\n"
L["Dungeons"] = "地下城"
L["Emissaries"] = "大使"
L["Emissary"] = "大使"
L["Empty Slot"] = "空插槽"
L["Enable"] = "开启"
L["Enable and set order in which characters are to be displayed"] = "开启和设置已显示角色的顺序"
L["Enable raids you want to see\n"] = "开启想要看到的团队副本\n"
L["Enable/Disable Currencies you want to see"] = "开启/停止想要看到的兑换通货"
L["Enable/Disable modules that you want to use"] = "开启/停止想要看到的模块"
L["EoA"] = "艾萨拉"
L["Exalted"] = "崇拜"
L["Expires in"] = "过期"
L["Extra Info Title Size"] = "额外信息标题大小"
L["Extra Tooltip Info"] = "额外鼠标提示信息"
L["February"] = "二月"
L["Feet"] = "脚"
L["Font"] = "字体"
L["Fonts"] = "文字"
L["Force Refresh"] = "强制重新整理"
L["Force Refresh World Quests"] = "强制重新整理世界任务"
L["Friendly"] = "友善"
L["Garrison mission progress"] = "要塞任务进度"
L["Gear"] = "装备"
L["General"] = "综合"
L["Gold"] = "金钱"
L["Got Mail!"] = "有新邮件!"
L["Hands"] = "手部"
L["Hated"] = "仇恨"
L["Head"] = "头部"
L["Head"] = "头部"
L["Hide empty currencies"] = "隐藏没有的兑换通货"
L["Hides currency if it's not present on character"] = "隐藏此角色没有的兑换通货"
L["Honor"] = "荣誉"
L["Honored"] = "尊敬"
L["Horizontal"] = "水平"
L["Hostile"] = "敌对"
L["HoV"] = "英灵殿"
L["Icon Alpha"] = "图标透明度"
L["Icon Scale"] = "图标大小缩放"
L["In Progress"] = "进行中"
L["Info Size"] = "信息大小"
L["Invalid QuestId"] = "无效的任务ID"
L["Invalid World Quest ID:"] = "无效的世界任务ID:"
L["Invasion Points"] = "侵略点"
L["Item"] = "物品"
L["Item Level"] = "物品等级"
L["January"] = "一月"
L["July"] = "七月"
L["June"] = "六月"
L["Key in bags"] = "现有钥匙"
L["Keystone"] = "钥匙"
L["Last Updated:"] = "最近更新:"
L["Legion"] = "军团再临"
L["Legs"] = "腿部"
L["Level"] = "等级"
L["Level"] = "等级"
L["LKara"] = "卡下"
L["Lock Icon"] = "锁定图标"
L["Mail"] = "邮件"
L["Main Hand"] = "主手"
L["March"] = "三月"
L["May"] = "五月"
L["Missions"] = "任务"
L["Mists of Pandaria"] = "熊猫人之谜"
L["Modules"] = "模块"
L["MoS"] = "噬魂"
L["Mythic Dungeons"] = "史诗地下城"
L["Mythic+"] = "大秘境"
L["Mythic+ Affixes"] = "大秘境词缀"
L["Mythic+ Key"] = "大秘境钥匙"
L["Mythic+ Weekly Affixes"] = "大秘境每周词缀"
L["Name"] = "名字"
L["Name"] = "名称"
L["Neck"] = "头部"
L["Neutral"] = "中立"
L["NL"] = "巢穴"
L["No Enchant!"] = "没有附魔!"
L["None"] = "无"
L["Not Available"] = "不可用"
L["Note"] = "备注"
L["Note!"] = "注意!"
L["November"] = "十一月"
L["Objectives"] = "任务目标"
L["October"] = "十月"
L["Off Hand"] = "副手"
L["Only current realm"] = "只有目前的服务器"
L["Or Select Faction"] = "或选择势力阵营"
L["Order"] = "顺序"
L["Order by item level"] = "按照物品等級排序"
L["Paragon"] = "巅峰"
L["Pick and choose reputations you want to see."] = "选择想要看到的声望。"
L["Pick reputation that are shown as main one for each character"] = "选择每个角色显示的主声望"
L["Professions"] = "专业"
L["Progress"] = "进度"
L["Quest Title"] = "任务标题"
L["Quests"] = "任务"
L["Quests Done This Week"] = "本周完成的任务"
L["RaiderIO M+ score"] = "RaiderIO M+ 分数"
L["RaiderIO M+ Score"] = "RaiderIO M+ 分数"
L["Raids"] = "团队副本"
L["Ranged"] = "远程"
L["Realm"] = "服务器"
L["Relic"] = "圣物"
L["Reputation"] = "声望"
L["Reputations"] = "声望"
L["Reset All Instances"] = "重置所有副本"
L["Revered"] = "崇敬"
L["Reward"] = "奖励"
L["Reward Name"] = "奖励名称"
L["Rewards"] = "奖励"
L["Ring"] = "戒指"
L["Save"] = "保存"
L["Select data you want to see in Extra tooltip"] = "选择要在鼠标提示中额外看到的信息"
L["Senders"] = "发件人"
L["September"] = "九月"
L["Shirt"] = "衬衣"
L["Shoulders"] = "肩膀"
L["Shoulders"] = "肩部"
L["Show Config"] = "显示设置选项"
L["Show Extra Info Tooltip"] = "显示额外的鼠标提示"
L["Show Icon"] = "显示图标"
L["Show in Extra Tooltip"] = "在鼠标提示中额外显示"
L["Show Minimap Icon"] = "显示小地图按钮"
L["Show only characters from currently logged in realm in tooltips"] = "鼠标提示中只显示目前服务器角色"
L["Show selected quests and their completetion in extra tooltip for current character"] = "在鼠标提示中额外显示选择的任务目前角色完成度"
L["Show Separate"] = "独立显示"
L["Slim Version"] = "窄版"
L["Slimmed down version of main tooltip i.e. +15 Neltharions Lair -> +15 NL\nMostly affects tooltip in horizontal orientation"] = "显示窄版鼠标提示，例如15奈萨里奥的巢穴->15巢穴\n对于水平方向鼠标提示的效果最明显"
L["SotT"] = "执政团"
L["Successfully deleted"] = "已成功删除"
L["The Burning Crusade"] = "燃烧的远征"
L["Time Left"] = "剩余时间"
L["Time Left: "] = "剩余时间: "
L["To add additional items/currency check out config!"] = "在设置选项中新增其他物品/兑换通货！"
L["Tooltip"] = "鼠标提示"
L["Tooltip Max Height"] = "鼠标提示最大高度"
L["Tooltip Orientation"] = "鼠标提示方向"
L["Tooltip Scale"] = "鼠标提示縮放大小"
L["Tracks available emissaries and their status for your character"] = "追踪角色可接的大使任务和状态"
L["Tracks characters mythic+ key in their bags and weekly mythic+ affixes"] = "追踪角色背包中的大秘境钥匙和大秘境每周词缀"
L["Tracks currently available bonus roll coins and amount of coins available from weekly quests"] = "追踪目前可用的额外好运符，及可获得的好运符数量"
L["Tracks Heart of Azeroth's current level and progress. Also show available traits."] = "追踪艾泽拉斯之心目前的等级与进度，并显示可用的特质"
L["Tracks highest completed mythic+ in a week and all highest level runs per dungeon"] = "追踪本CD内完成的最佳大秘境成绩及每个地下城的最高等级"
L["Tracks incoming mail"] = "追踪新寄来的邮件"
L["Tracks lockouts for current expansion raids"] = "追踪当前资料片团队进度状态"
L["Tracks user specified world quests. Provides information like - Time Left, Reward and availability for current character"] = "追踪指定的世界任务。根据剩余时间、奖励、当前角色可做...等信息"
L["Tracks weekly completed mythic dungeons"] = "追踪每CD完成的史诗地下城"
L["Tracks World Boss availability for each character."] = "追踪每个角色可打的世界boss"
L["trait"] = "特质"
L["traits"] = "特质"
L["Trinket"] = "饰品"
L["Type"] = "类型"
L["UKara"] = "卡上"
L["Unfriendly"] = "不友好"
L["Unknown"] = "未知"
L["Uses Raider.IO addon (Needs to be installed) to display your m+ score"] = "使用 Raider.IO 插件 (需要另外安裝) 来显示大秘境分数"
L["Vanilla"] = "经典旧世"
L["Version"] = "版本"
L["Vertical"] = "垂直"
L["VotW"] = "地窟"
L["Waist"] = "腰带"
L["Warlords of Draenor"] = "德拉诺之王"
L["Weekly"] = "每周"
L["Weekly reset in: "] = "每周重置于: "
L["Weekly/Daily Quests"] = "每周/每日任务"
L["World Bosses"] = "世界boss"
L["World Quests"] = "世界任务"
L["Wrath of The Lich King"] = "巫妖王之怒"
L["Wrists"] = "护腕"
L["Custom"] = "自定义"
L["Reward Type"] = "奖励类型"
L["Add Note"] = "新增备注"
L[' level'] = " 等级"
L["Exlist"] = "小号列表"
L["Exlist "] = "我的小号列表"
L["Allows to select different reputation progress for your characters"] = "允许角色选择不同的声望进度"
L["Weekly Islands"] = "海岛"
L["Completed"] = "已完成"
L["Turn In!"] = "交任务!"
L["Show Islands Weekly"] = "显示海岛周常"
L["Show characters progress with weekly Islands Expedition quest"] = "显示角色的海岛周常任务进度"
L["Reward Amount"] = "奖励数量"
L["AD"] = "阿塔"
L["FH"] = "自由镇"
L["TD"] = "监狱"
L["MOTHER"] = "矿区"
L["WM"] = "庄园"
L["KR"] = "诸王"
L["ToS"] = "神庙"
L["URot"] = "地渊"
L["SotS"] = "风暴"
L["SoB"] = "围攻"
L["Halls of Containment"] = "抑制大厅"
L["Crimson Descent"] = "猩红深渊"
L["Heart of Corruption"] = "腐蚀之心"`

The translation of simplified chinese has been updated.

**Comment by sragia** [comment]
Hey, thanks a lot for translation.
Enabled [curse localization](https://wow.curseforge.com/projects/exlist/localization) and imported it.
It should be up in latest release

Cheers

**Comment by CrisReus** [comment]
I am very glad to use curse localization.
